// data.ts
import { CharacterParts } from './types';

export const characterParts: CharacterParts = {
  background: [
    { id: 0, name: 'Blue', image: '/assets/background/blue.png' },
    { id: 1, name: 'Green', image: '/assets/background/green.png' },
    { id: 2, name: 'Orange', image: '/assets/background/orange.png' },
    { id: 3, name: 'Purple', image: '/assets/background/purple.png' },
    { id: 4, name: 'Red', image: '/assets/background/red.png' },
    { id: 5, name: 'Yellow', image: '/assets/background/yellow.png' },
    // add more backgrounds
  ],
  type: [
    { id: 0, name: 'Alien', image: '/assets/type/alien.png' },
    { id: 1, name: 'Brown', image: '/assets/type/brown.png' },
    { id: 2, name: 'Dark', image: '/assets/type/dark.png' },
    { id: 3, name: 'Orange', image: '/assets/type/orange.png' },
    { id: 4, name: 'Purple', image: '/assets/type/purple.png' },
    { id: 5, name: 'Red', image: '/assets/type/red.png' },
    { id: 6, name: 'Skeleton', image: '/assets/type/skeleton.png' },
    { id: 7, name: 'Solana', image: '/assets/type/solana.png' },
    { id: 8, name: 'Zombie', image: '/assets/type/zombie.png' },

    // add more bodies
  ],
  hats: [
    { id: 0, name: 'Admiral Hat', image: '/assets/hats/none.png' },
    { id: 1, name: 'Bandana Ninja', image: '/assets/hats/bandana-ninja.png' },
    { id: 2, name: 'Bandana Ninja', image: '/assets/hats/biege-tophat.png' },
    { id: 3, name: 'Bandana Ninja', image: '/assets/hats/black-backwards-cap.png' },
    { id: 4, name: 'Bandana Ninja', image: '/assets/hats/black-bandana.png' },
    { id: 5, name: 'Bandana Ninja', image: '/assets/hats/black-cap.png' },
    { id: 6, name: 'Bandana Ninja', image: '/assets/hats/black-fedora-1.png' },
    { id: 7, name: 'Bandana Ninja', image: '/assets/hats/black-fedora-2.png' },
    { id: 8, name: 'Bandana Ninja', image: '/assets/hats/black-protagonist-hat.png' },
    { id: 9, name: 'Bandana Ninja', image: '/assets/hats/black-tophat.png' },
    { id: 10, name: 'Bandana Ninja', image: '/assets/hats/blue-backwards-cap.png' },
    { id: 11, name: 'Bandana Ninja', image: '/assets/hats/blue-cap.png' },
    { id: 12, name: 'Bandana Ninja', image: '/assets/hats/blue-punk-hair.png' },
    { id: 13, name: 'Bandana Ninja', image: '/assets/hats/cop-hat.png' },
    { id: 14, name: 'Bandana Ninja', image: '/assets/hats/cowboy-hat.png' },
    { id: 15, name: 'Bandana Ninja', image: '/assets/hats/crown.png' },
    { id: 16, name: 'Bandana Ninja', image: '/assets/hats/firefighter-hat.png' },
    { id: 17, name: 'Bandana Ninja', image: '/assets/hats/flower.png' },
    { id: 18, name: 'Bandana Ninja', image: '/assets/hats/green-backwards-cap.png' },
    { id: 19, name: 'Bandana Ninja', image: '/assets/hats/green-beret.png' },
    { id: 20, name: 'Bandana Ninja', image: '/assets/hats/green-cap.png' },
    { id: 21, name: 'Bandana Ninja', image: '/assets/hats/green-punk-hair.png' },
    { id: 22, name: 'Bandana Ninja', image: '/assets/hats/green-tophat.png' },
    { id: 23, name: 'Bandana Ninja', image: '/assets/hats/halo.png' },
    { id: 24, name: 'Bandana Ninja', image: '/assets/hats/military-hat.png' },
    { id: 25, name: 'Bandana Ninja', image: '/assets/hats/mining-hat.png' },
    { id: 26, name: 'Bandana Ninja', image: '/assets/hats/mugiwara-hat.png' },
    { id: 27, name: 'Bandana Ninja', image: '/assets/hats/admiral-hat.png' },
    { id: 28, name: 'Bandana Ninja', image: '/assets/hats/orange-cap-backwards.png' },
    { id: 29, name: 'Bandana Ninja', image: '/assets/hats/orange-cap.png' },
    { id: 30, name: 'Bandana Ninja', image: '/assets/hats/pirate-hat.png' },
    { id: 31, name: 'Bandana Ninja', image: '/assets/hats/purple-backwards-cap.png' },
    { id: 32, name: 'Bandana Ninja', image: '/assets/hats/purple-cap.png' },
    { id: 33, name: 'Bandana Ninja', image: '/assets/hats/red-backwards-cap.png' },
    { id: 34, name: 'Bandana Ninja', image: '/assets/hats/red-beret.png' },
    { id: 35, name: 'Bandana Ninja', image: '/assets/hats/red-cap.png' },
    { id: 36, name: 'Bandana Ninja', image: '/assets/hats/red-punk-hair.png' },
    { id: 37, name: 'Bandana Ninja', image: '/assets/hats/sailor-cap.png' },
    { id: 38, name: 'Bandana Ninja', image: '/assets/hats/solana-backwards-cap.png' },{ id: 1, name: 'Bandana Ninja', image: '/assets/hats/bandana-ninja.png' },
    { id: 39, name: 'Bandana Ninja', image: '/assets/hats/solana-cap.png' },
    { id: 40, name: 'Bandana Ninja', image: '/assets/hats/sombrero.png' },
    { id: 41, name: 'Bandana Ninja', image: '/assets/hats/space-warrior.png' },
    { id: 42, name: 'Bandana Ninja', image: '/assets/hats/thief-hat.png' },
    { id: 43, name: 'Bandana Ninja', image: '/assets/hats/viking-helmet.png' },
    { id: 44, name: 'Bandana Ninja', image: '/assets/hats/white-fedora-1.png' },
    { id: 45, name: 'Bandana Ninja', image: '/assets/hats/white-fedora-2.png' },
    { id: 46, name: 'Bandana Ninja', image: '/assets/hats/white-protagonist-hat.png' },
    // add more hats
  ],
  clothes: [
    { id: 0, name: 'Cop Vest', image: '/assets/clothes/none.png' },
    { id: 1, name: 'Cop Vest', image: '/assets/clothes/biege-smoking.png' },
    { id: 2, name: 'Cop Vest', image: '/assets/clothes/biker-vest.png' },
    { id: 3, name: 'Cop Vest', image: '/assets/clothes/black-kimono.png' },
    { id: 4, name: 'Cop Vest', image: '/assets/clothes/black-smoking.png' },
    { id: 5, name: 'Cop Vest', image: '/assets/clothes/green-shirt.png' },
    { id: 6, name: 'Cop Vest', image: '/assets/clothes/blue-shirt.png' },
    { id: 7, name: 'Cop Vest', image: '/assets/clothes/brown-jacket.png' },
    { id: 8, name: 'Cop Vest', image: '/assets/clothes/diamond.png' },
    { id: 9, name: 'Cop Vest', image: '/assets/clothes/green-jacket.png' },
    { id: 10, name: 'Cop Vest', image: '/assets/clothes/military-vest.png' },
    { id: 11, name: 'Cop Vest', image: '/assets/clothes/cop-vest.png' },
    { id: 12, name: 'Cop Vest', image: '/assets/clothes/orange-jacket.png' },
    { id: 13, name: 'Cop Vest', image: '/assets/clothes/orange-kimono.png' },
    { id: 14, name: 'Cop Vest', image: '/assets/clothes/orange-shirt.png' },
    { id: 15, name: 'Cop Vest', image: '/assets/clothes/pirate-vest.png' },
    { id: 16, name: 'Cop Vest', image: '/assets/clothes/poncho.png' },
    { id: 17, name: 'Cop Vest', image: '/assets/clothes/purple-shirt.png' },
    { id: 18, name: 'Cop Vest', image: '/assets/clothes/red-shirt.png' },
    { id: 19, name: 'Cop Vest', image: '/assets/clothes/roman-armor.png' },
    { id: 20, name: 'Cop Vest', image: '/assets/clothes/sailor-vest.png' },
    { id: 21, name: 'Cop Vest', image: '/assets/clothes/white-shirt.png' },
    { id: 22, name: 'Cop Vest', image: '/assets/clothes/green-smoking.png' },
    // add more clothing items
  ],
  eyes: [
    { id: 0, name: 'Eyes 1', image: '/assets/eyes/none.png' },
    { id: 1, name: 'Eyes 1', image: '/assets/eyes/cool-glasses.png' },
    { id: 2, name: 'Eyes 1', image: '/assets/eyes/gold-glasses.png' },
    { id: 3, name: 'Eyes 1', image: '/assets/eyes/green-glasses.png' },
    { id: 4, name: 'Eyes 1', image: '/assets/eyes/laser-eyes.png' },
    { id: 5, name: 'Eyes 1', image: '/assets/eyes/3d-glasses.png' },
    { id: 6, name: 'Eyes 1', image: '/assets/eyes/purple-glasses.png' },
    { id: 7, name: 'Eyes 1', image: '/assets/eyes/solana-vipers.png' },
    { id: 8, name: 'Eyes 1', image: '/assets/eyes/vipers.png' },
    { id: 9, name: 'Eyes 1', image: '/assets/eyes/vr.png' },
    { id: 10, name: 'Eyes 1', image: '/assets/eyes/yellow-glasses.png' },
    { id: 11, name: 'Eyes 1', image: '/assets/eyes/vr-blue.png' },
    { id: 12, name: 'Eyes 1', image: '/assets/eyes/vr-gray.png' },
    { id: 13, name: 'Eyes 1', image: '/assets/eyes/vr-lime.png' },
    { id: 14, name: 'Eyes 1', image: '/assets/eyes/vr-orange.png' },
    { id: 15, name: 'Eyes 1', image: '/assets/eyes/vr-pink.png' },
    { id: 16, name: 'Eyes 1', image: '/assets/eyes/vr-solana.png' },
    { id: 17, name: 'Eyes 1', image: '/assets/eyes/vr-viper.png' },
    // add more eyes
  ],
  mouth: [
    { id: 0, name: 'Mouth 1', image: '/assets/mouth/none.png' },
    { id: 1, name: 'Mouth 1', image: '/assets/mouth/cigarette.png' },
    { id: 2, name: 'Mouth 1', image: '/assets/mouth/pipe.png' },
    { id: 3, name: 'Mouth 1', image: '/assets/mouth/vape.png' },
    // add more mouths
  ],
};
