// data.ts
import { CharacterParts } from './types';

export const characterParts: CharacterParts = {
  background: [
    { id: 0, name: 'Blue', image: '/assets/background/blue.png' },
    { id: 1, name: 'Green', image: '/assets/background/green.png' },
    { id: 2, name: 'Orange', image: '/assets/background/orange.png' },
    { id: 3, name: 'Purple', image: '/assets/background/purple.png' },
    { id: 4, name: 'Red', image: '/assets/background/red.png' },
    { id: 5, name: 'Yellow', image: '/assets/background/yellow.png' },
    { id: 6, name: 'BTC Orange', image: '/assets/background/btc-orange.png' },
    { id: 7, name: 'GM Green', image: '/assets/background/gm-green.png' },
    { id: 8, name: 'GM Orange', image: '/assets/background/gm-orange.png' },
    { id: 9, name: 'GM Red', image: '/assets/background/gm-red.png' },
    { id: 10, name: 'GM Yellow', image: '/assets/background/gm-yellow.png' },
    { id: 11, name: 'GM Purple', image: '/assets/background/gm-purple.png' },
    { id: 12, name: 'GM White', image: '/assets/background/gm-white.png' },
    { id: 13, name: 'GM BTC', image: '/assets/background/gm-btc.png' },
    // add more backgrounds
  ],
  type: [
    { id: 0, name: 'Alien', image: '/assets/type/alien.png' },
    { id: 1, name: 'Brown', image: '/assets/type/brown.png' },
    { id: 2, name: 'Dark', image: '/assets/type/dark.png' },
    { id: 3, name: 'Orange', image: '/assets/type/orange.png' },
    { id: 4, name: 'Purple', image: '/assets/type/purple.png' },
    { id: 5, name: 'Red', image: '/assets/type/red.png' },
    { id: 6, name: 'Skeleton', image: '/assets/type/skeleton.png' },
    { id: 7, name: 'Solana', image: '/assets/type/solana.png' },
    { id: 8, name: 'Zombie', image: '/assets/type/zombie.png' },
    // add more types
  ],
  hats: [
    { id: 0, name: 'Admiral Hat', image: '/assets/hats/none.png' },
    { id: 1, name: 'Bandana Ninja', image: '/assets/hats/bandana-ninja.png' },
    { id: 2, name: 'Biege Tophat', image: '/assets/hats/biege-tophat.png' },
    { id: 3, name: 'Black Backwards Cap', image: '/assets/hats/black-backwards-cap.png' },
    { id: 4, name: 'Black Bandana', image: '/assets/hats/black-bandana.png' },
    { id: 5, name: 'Black Cap', image: '/assets/hats/black-cap.png' },
    { id: 6, name: 'Black Fedora 1', image: '/assets/hats/black-fedora-1.png' },
    { id: 7, name: 'Black Fedora 2', image: '/assets/hats/black-fedora-2.png' },
    { id: 8, name: 'Black Protagonist Hat', image: '/assets/hats/black-protagonist-hat.png' },
    { id: 9, name: 'Black Tophat', image: '/assets/hats/black-tophat.png' },
    { id: 10, name: 'Blue Backwards Cap', image: '/assets/hats/blue-backwards-cap.png' },
    { id: 11, name: 'Blue Cap', image: '/assets/hats/blue-cap.png' },
    { id: 12, name: 'Blue Punk Hair', image: '/assets/hats/blue-punk-hair.png' },
    { id: 13, name: 'Cop Hat', image: '/assets/hats/cop-hat.png' },
    { id: 14, name: 'Cowboy Hat', image: '/assets/hats/cowboy-hat.png' },
    { id: 15, name: 'Crown', image: '/assets/hats/crown.png' },
    { id: 16, name: 'Firefighter Hat', image: '/assets/hats/firefighter-hat.png' },
    { id: 17, name: 'Flower', image: '/assets/hats/flower.png' },
    { id: 18, name: 'Green Backwards Cap', image: '/assets/hats/green-backwards-cap.png' },
    { id: 19, name: 'Green Beret', image: '/assets/hats/green-beret.png' },
    { id: 20, name: 'Green Cap', image: '/assets/hats/green-cap.png' },
    { id: 21, name: 'Green Punk Hair', image: '/assets/hats/green-punk-hair.png' },
    { id: 22, name: 'Green Tophat', image: '/assets/hats/green-tophat.png' },
    { id: 23, name: 'Halo', image: '/assets/hats/halo.png' },
    { id: 24, name: 'Military Hat', image: '/assets/hats/military-hat.png' },
    { id: 25, name: 'Mining Hat', image: '/assets/hats/mining-hat.png' },
    { id: 26, name: 'Mugiwara Hat', image: '/assets/hats/mugiwara-hat.png' },
    { id: 27, name: 'Orange Bandana', image: '/assets/hats/admiral-hat.png' },
    { id: 28, name: 'Orange Backwards Cap', image: '/assets/hats/orange-cap-backwards.png' },
    { id: 29, name: 'Orange Cap', image: '/assets/hats/orange-cap.png' },
    { id: 30, name: 'Pirate Hat', image: '/assets/hats/pirate-hat.png' },
    { id: 31, name: 'Purple Backwards Cap', image: '/assets/hats/purple-backwards-cap.png' },
    { id: 32, name: 'Purple Cap', image: '/assets/hats/purple-cap.png' },
    { id: 33, name: 'Red Backwards Cap', image: '/assets/hats/red-backwards-cap.png' },
    { id: 34, name: 'Red Beret', image: '/assets/hats/red-beret.png' },
    { id: 35, name: 'Red Cap', image: '/assets/hats/red-cap.png' },
    { id: 36, name: 'Red Punk Hair', image: '/assets/hats/red-punk-hair.png' },
    { id: 37, name: 'Sailor Cap', image: '/assets/hats/sailor-cap.png' },
    { id: 38, name: 'Solana Backwards Cap', image: '/assets/hats/solana-backwards-cap.png' },
    { id: 39, name: 'Solana Cap', image: '/assets/hats/solana-cap.png' },
    { id: 40, name: 'Sombrero', image: '/assets/hats/sombrero.png' },
    { id: 41, name: 'Space Warrior', image: '/assets/hats/space-warrior.png' },
    { id: 42, name: 'Thief Hat', image: '/assets/hats/thief-hat.png' },
    { id: 43, name: 'Viking Helmet', image: '/assets/hats/viking-helmet.png' },
    { id: 44, name: 'White Fedora 1', image: '/assets/hats/white-fedora-1.png' },
    { id: 45, name: 'White Fedora 2', image: '/assets/hats/white-fedora-2.png' },
    { id: 46, name: 'White Protagonist Hat', image: '/assets/hats/white-protagonist-hat.png' },
    { id: 47, name: 'McBeef', image: '/assets/hats/mcbeef.png' },
    { id: 48, name: 'McBeret', image: '/assets/hats/mcberet.png' },
    { id: 49, name: 'McCap', image: '/assets/hats/mccap.png' },
    { id: 50, name: 'McFedora1', image: '/assets/hats/mcfedora1.png' },
    { id: 51, name: 'McFedora2', image: '/assets/hats/mcfedora2.png' },
    { id: 52, name: 'McFish', image: '/assets/hats/mcfish.png' },
    { id: 53, name: 'McFlower', image: '/assets/hats/mcflower.png' },
    { id: 54, name: 'McFro', image: '/assets/hats/mcfro.png' },
    { id: 55, name: 'McHalo', image: '/assets/hats/mchalo.png' },
    { id: 56, name: 'McHeadset', image: '/assets/hats/mcheadset.png' },
    { id: 57, name: 'McHero', image: '/assets/hats/mchero.png' },
    { id: 58, name: 'McKing', image: '/assets/hats/mcking.png' },
    { id: 59, name: 'McMiner', image: '/assets/hats/mcminer.png' },
    { id: 60, name: 'McNinja', image: '/assets/hats/mcninja.png' },
    { id: 61, name: 'McPig', image: '/assets/hats/mcpig.png' },
    { id: 62, name: 'McPirate', image: '/assets/hats/mcpirate.png' },
    { id: 63, name: 'McReverse', image: '/assets/hats/mcreverse.png' },
    { id: 64, name: 'McRobber', image: '/assets/hats/mcrobber.png' },
    { id: 65, name: 'McTaco', image: '/assets/hats/mctaco.png' },
    { id: 66, name: 'McTophat', image: '/assets/hats/mctophat.png' },
    { id: 67, name: 'McViking', image: '/assets/hats/mcviking.png' },
    { id: 68, name: 'McVisor', image: '/assets/hats/mcvisor.png' }
    // add more hats
  ],
  clothes: [
    { id: 0, name: 'None', image: '/assets/clothes/none.png' },
    { id: 1, name: 'Beige Smoking', image: '/assets/clothes/biege-smoking.png' },
    { id: 2, name: 'Biker Vest', image: '/assets/clothes/biker-vest.png' },
    { id: 3, name: 'Black Kimono', image: '/assets/clothes/black-kimono.png' },
    { id: 4, name: 'Black Smoking', image: '/assets/clothes/black-smoking.png' },
    { id: 5, name: 'Green Shirt', image: '/assets/clothes/green-shirt.png' },
    { id: 6, name: 'Blue Shirt', image: '/assets/clothes/blue-shirt.png' },
    { id: 7, name: 'Brown Jacket', image: '/assets/clothes/brown-jacket.png' },
    { id: 8, name: 'Diamond', image: '/assets/clothes/diamond.png' },
    { id: 9, name: 'Green Jacket', image: '/assets/clothes/green-jacket.png' },
    { id: 10, name: 'Military Vest', image: '/assets/clothes/military-vest.png' },
    { id: 11, name: 'Cop Vest', image: '/assets/clothes/cop-vest.png' },
    { id: 12, name: 'Orange Jacket', image: '/assets/clothes/orange-jacket.png' },
    { id: 13, name: 'Orange Kimono', image: '/assets/clothes/orange-kimono.png' },
    { id: 14, name: 'Orange Shirt', image: '/assets/clothes/orange-shirt.png' },
    { id: 15, name: 'Pirate Vest', image: '/assets/clothes/pirate-vest.png' },
    { id: 16, name: 'Poncho', image: '/assets/clothes/poncho.png' },
    { id: 17, name: 'Purple Shirt', image: '/assets/clothes/purple-shirt.png' },
    { id: 18, name: 'Red Shirt', image: '/assets/clothes/red-shirt.png' },
    { id: 19, name: 'Roman Armor', image: '/assets/clothes/roman-armor.png' },
    { id: 20, name: 'Sailor Vest', image: '/assets/clothes/sailor-vest.png' },
    { id: 21, name: 'White Shirt', image: '/assets/clothes/white-shirt.png' },
    { id: 22, name: 'Green Smoking', image: '/assets/clothes/green-smoking.png' }
    // add more clothes
  ],
  eyes: [
    { id: 0, name: 'None', image: '/assets/eyes/none.png' },
    { id: 1, name: 'VR', image: '/assets/eyes/vr.png' },
    { id: 2, name: 'Gold Glasses', image: '/assets/eyes/gold-glasses.png' },
    { id: 3, name: 'Green Glasses', image: '/assets/eyes/green-glasses.png' },
    { id: 4, name: 'Laser Eyes', image: '/assets/eyes/laser-eyes.png' },
    { id: 5, name: '3D Glasses', image: '/assets/eyes/3d-glasses.png' },
    { id: 6, name: 'Purple Glasses', image: '/assets/eyes/purple-glasses.png' },
    { id: 7, name: 'Solana Vipers', image: '/assets/eyes/solana-vipers.png' },
    { id: 8, name: 'Vipers', image: '/assets/eyes/vipers.png' },
    { id: 9, name: 'Cool Glasses', image: '/assets/eyes/cool-glasses.png' },
    { id: 10, name: 'Yellow Glasses', image: '/assets/eyes/yellow-glasses.png' },
    
    // add more eyes
  ],
  mouth: [
    { id: 0, name: 'None', image: '/assets/mouth/none.png' },
    { id: 1, name: 'Cigarette', image: '/assets/mouth/cigarette.png' },
    { id: 2, name: 'Pipe', image: '/assets/mouth/pipe.png' },
    { id: 3, name: 'Vape', image: '/assets/mouth/vape.png' },
    // add more mouths
  ],
  special: [
    { id: 0, name: 'None', image: '/assets/special/none.png'},
    { id: 1, name: 'Gun', image: '/assets/special/gun.png'},
    { id: 2, name: 'Guns', image: '/assets/special/guns.png'},
    { id: 3, name: 'Space Blue', image: '/assets/special/space-blue.png'},
    { id: 4, name: 'Space Green', image: '/assets/special/space-green.png'},
    { id: 5, name: 'Space Orange', image: '/assets/special/space-orange.png'},
    { id: 6, name: 'Space Purple', image: '/assets/special/space-purple.png'},
    { id: 7, name: 'Space Red', image: '/assets/special/space-red.png'},
    { id: 8, name: 'Space Yellow', image: '/assets/special/space-yellow.png'},
    { id: 9, name: 'FU', image: '/assets/special/fu.png'},
    { id: 10, name: 'FU', image: '/assets/special/aladdin.png'},
    { id: 11, name: 'FU', image: '/assets/special/alien.png'},
    { id: 12, name: 'FU', image: '/assets/special/batman.png'},
    { id: 13, name: 'FU', image: '/assets/special/chef.png'},
    { id: 14, name: 'FU', image: '/assets/special/dark.png'},
    { id: 15, name: 'FU', image: '/assets/special/detective.png'},
    { id: 16, name: 'FU', image: '/assets/special/jason.png'},
    { id: 17, name: 'FU', image: '/assets/special/luigi.png'},
    { id: 18, name: 'FU', image: '/assets/special/mario.png'},
    { id: 19, name: 'FU', image: '/assets/special/mib.png'},
    { id: 20, name: 'FU', image: '/assets/special/nurse.png'},
    { id: 21, name: 'FU', image: '/assets/special/orange.png'},
    { id: 22, name: 'FU', image: '/assets/special/pirate.png'},
    { id: 23, name: 'FU', image: '/assets/special/pocoyo.png'},
    { id: 24, name: 'FU', image: '/assets/special/pumpkin.png'},
    { id: 25, name: 'FU', image: '/assets/special/purple.png'},
    { id: 26, name: 'FU', image: '/assets/special/red.png'},
    { id: 27, name: 'FU', image: '/assets/special/robber.png'},
    { id: 28, name: 'FU', image: '/assets/special/skeleton.png'},
    { id: 29, name: 'FU', image: '/assets/special/snake.png'},
    { id: 30, name: 'FU', image: '/assets/special/solana.png'},
    { id: 31, name: 'FU', image: '/assets/special/wario.png'},
    { id: 32, name: 'FU', image: '/assets/special/wizard.png'},
    { id: 33, name: 'FU', image: '/assets/special/zombie.png'},
  ],
  vr: [
    { id: 0, name: 'None', image: '/assets/vr/none.png' },
    { id: 1, name: 'VR Blue Eyes', image: '/assets/vr/vr-blue.png' },
    { id: 2, name: 'VR Gray Eyes', image: '/assets/vr/vr-gray.png' },
    { id: 3, name: 'VR Lime Eyes', image: '/assets/vr/vr-lime.png' },
    { id: 4, name: 'VR Orange Eyes', image: '/assets/vr/vr-orange.png' },
    { id: 5, name: 'VR Pink Eyes', image: '/assets/vr/vr-pink.png' },
    { id: 6, name: 'VR Solana Eyes', image: '/assets/vr/vr-solana.png' },
    { id: 7, name: 'VR Viper Eyes', image: '/assets/vr/vr-viper.png' },
    { id: 8, name: 'VR Gold Eyes', image: '/assets/vr/vr-gold.png' },
    { id: 9, name: 'VR', image: '/assets/vr/vr.png' },

  ]
};
